version: "3.7"

networks:
  project-net:

services:
  nginx:
    image: nginx:1.27
    working_dir: /var/www
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './public:/var/www/public'
      - './storage/app:/var/www/storage/app:cached'
      - './docker/nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf'
      - './letsencrypt:/etc/letsencrypt'  # Persist certificates
      - './logs/nginx:/var/log/nginx'
    networks:
      - project-net

  rate-monitor:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile.monitor
    volumes:
      - './logs/nginx:/var/log/nginx'
    environment:
      - EMAIL_TO=akram.tj1@gmail.com  # Change this to your email
    networks:
      - project-net

  php-fpm:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - UID=${UID-1001}
        - GID=${GID-1001}
    image: php-fpm
    working_dir: /var/www
    volumes:
      - './:/var/www/'
    user: "${UID}:${GID}"
    networks:
      - project-net

  mysql:
    image: mysql:8.1.0
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - './storage/db-data:/var/lib/mysql'
    networks:
      - project-net

  node:
    build:
      context: ./docker/nodejs
      dockerfile: Dockerfile
    links:
      - php-fpm
      - nginx
    volumes:
      - "./:/var/www/html:cached"
    working_dir: /var/www/html
    tty: true
    ports:
      - ${NODE_PORT-8080}:${NODE_PORT-8080}
      - "5173:5173"
    expose:
      - ${NODE_PORT-8080}
      - "5173"
    environment:
      HOST: "0.0.0.0"
      GIT_SSL_NO_VERIFY: "true"
    image: node
    networks:
      - project-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - project-net
